import {
  CitySchema,
  CountrySchema,
  CourseSchema,
  PlaceSchema,
  PlaceSnapshotSchema,
  YouTuberSchema,
} from '../../../../packages/domain/src/entities.ts';

const sourceReferences = {
  paniTokyo: [
    {
      id: 'source-course-pani-tokyo',
      type: 'youtube_caption',
      label: 'Pani Bottle Tokyo capsule trip',
      url: 'https://www.youtube.com/watch?v=pani-tokyo',
      verificationLevel: 'high',
    },
  ],
  kwakFukuoka: [
    {
      id: 'source-course-kwak-fukuoka',
      type: 'youtube_caption',
      label: 'KwakTube Fukuoka food crawl',
      url: 'https://www.youtube.com/watch?v=kwak-fukuoka',
      verificationLevel: 'high',
    },
  ],
  wonjiHanoi: [
    {
      id: 'source-course-wonji-hanoi',
      type: 'youtube_description',
      label: "Wonji's Diary Hanoi slow travel",
      url: 'https://www.youtube.com/watch?v=wonji-hanoi',
      verificationLevel: 'medium',
    },
  ],
  sionDaNang: [
    {
      id: 'source-course-sion-danang',
      type: 'youtube_caption',
      label: 'Nomad Sion Da Nang beach route',
      url: 'https://www.youtube.com/watch?v=sion-danang',
      verificationLevel: 'high',
    },
  ],
  czechjTokyo: [
    {
      id: 'source-course-czechj-tokyo',
      type: 'blog',
      label: 'Czechj Tokyo city notes',
      url: 'https://blog.example.com/czechj-tokyo',
      verificationLevel: 'medium',
    },
  ],
  janjanHanoi: [
    {
      id: 'source-course-janjan-hanoi',
      type: 'youtube_caption',
      label: 'JanjanBari Hanoi overnight route',
      url: 'https://www.youtube.com/watch?v=janjan-hanoi',
      verificationLevel: 'high',
    },
  ],
} as const;

export const curatedYouTubers = [
  YouTuberSchema.parse({
    id: 'youtuber-pani-bottle',
    channelName: 'Pani Bottle',
    displayName: '빠니보틀',
    youtubeChannelUrl: 'https://www.youtube.com/@PaniBottle',
    profileImageUrl: 'https://images.example.com/youtubers/pani-bottle.png',
    description: 'Long-form backpacking travel stories',
    isActive: true,
    tags: ['backpacking', 'global', '일본'],
  }),
  YouTuberSchema.parse({
    id: 'youtuber-kwaktube',
    channelName: 'KwakTube',
    displayName: '곽튜브',
    youtubeChannelUrl: 'https://www.youtube.com/@KwakTube',
    profileImageUrl: 'https://images.example.com/youtubers/kwaktube.png',
    description: 'Street food and local culture focused travel',
    isActive: true,
    tags: ['food', 'city'],
  }),
  YouTuberSchema.parse({
    id: 'youtuber-wonji',
    channelName: "Wonji's Diary",
    displayName: '원지의하루',
    youtubeChannelUrl: 'https://www.youtube.com/@WonjisDiary',
    profileImageUrl: 'https://images.example.com/youtubers/wonji.png',
    description: 'Gentle itinerary and lodging focused vlogs',
    isActive: true,
    tags: ['solo', 'lodging'],
  }),
  YouTuberSchema.parse({
    id: 'youtuber-sion',
    channelName: 'Nomad Sion',
    displayName: '노마드션',
    youtubeChannelUrl: 'https://www.youtube.com/@NomadSion',
    profileImageUrl: 'https://images.example.com/youtubers/sion.png',
    description: 'Digital nomad style routes and work-friendly spots',
    isActive: true,
    tags: ['nomad', 'coastal'],
  }),
  YouTuberSchema.parse({
    id: 'youtuber-czechj',
    channelName: 'Czechj',
    displayName: '체코제이',
    youtubeChannelUrl: 'https://www.youtube.com/@Czechj',
    profileImageUrl: 'https://images.example.com/youtubers/czechj.png',
    description: 'Urban neighborhood and local attraction picks',
    isActive: true,
    tags: ['urban', 'walking'],
  }),
  YouTuberSchema.parse({
    id: 'youtuber-janjanbari',
    channelName: 'JanjanBari',
    displayName: '잔잔바리',
    youtubeChannelUrl: 'https://www.youtube.com/@JanjanBari',
    profileImageUrl: 'https://images.example.com/youtubers/janjanbari.png',
    description: 'Compact overnight travel routes and practical stays',
    isActive: true,
    tags: ['budget', 'overnight'],
  }),
];

export const countries = [
  CountrySchema.parse({
    id: 'country-jp',
    code: 'JP',
    nameKo: '일본',
    nameEn: 'Japan',
    thumbnailUrl: 'https://images.example.com/countries/japan.png',
  }),
  CountrySchema.parse({
    id: 'country-vn',
    code: 'VN',
    nameKo: '베트남',
    nameEn: 'Vietnam',
    thumbnailUrl: 'https://images.example.com/countries/vietnam.png',
  }),
];

export const cities = [
  CitySchema.parse({
    id: 'city-tokyo',
    countryId: 'country-jp',
    nameKo: '도쿄',
    nameEn: 'Tokyo',
    latitude: 35.6762,
    longitude: 139.6503,
    thumbnailUrl: 'https://images.example.com/cities/tokyo.png',
  }),
  CitySchema.parse({
    id: 'city-fukuoka',
    countryId: 'country-jp',
    nameKo: '후쿠오카',
    nameEn: 'Fukuoka',
    latitude: 33.5902,
    longitude: 130.4017,
    thumbnailUrl: 'https://images.example.com/cities/fukuoka.png',
  }),
  CitySchema.parse({
    id: 'city-hanoi',
    countryId: 'country-vn',
    nameKo: '하노이',
    nameEn: 'Hanoi',
    latitude: 21.0278,
    longitude: 105.8342,
    thumbnailUrl: 'https://images.example.com/cities/hanoi.png',
  }),
  CitySchema.parse({
    id: 'city-danang',
    countryId: 'country-vn',
    nameKo: '다낭',
    nameEn: 'Da Nang',
    latitude: 16.0544,
    longitude: 108.2022,
    thumbnailUrl: 'https://images.example.com/cities/danang.png',
  }),
];

export const places = [
  PlaceSchema.parse({
    id: 'place-tokyo-1',
    cityId: 'city-tokyo',
    countryId: 'country-jp',
    name: 'Tsukiji Outer Market',
    category: 'restaurant',
    shortDescription: 'Seafood breakfast market stop',
    address: '4 Chome-16-2 Tsukiji, Chuo City, Tokyo',
    location: { lat: 35.6655, lng: 139.7708 },
    thumbnailUrl: 'https://images.example.com/places/tsukiji-market.png',
    tags: ['breakfast', 'market'],
    sourceReferences: sourceReferences.paniTokyo,
  }),
  PlaceSchema.parse({
    id: 'place-tokyo-2',
    cityId: 'city-tokyo',
    countryId: 'country-jp',
    name: 'Senso-ji',
    category: 'attraction',
    shortDescription: 'Historic temple route anchor',
    address: '2 Chome-3-1 Asakusa, Taito City, Tokyo',
    location: { lat: 35.7148, lng: 139.7967 },
    thumbnailUrl: 'https://images.example.com/places/sensoji.png',
    tags: ['temple', 'walking'],
    sourceReferences: sourceReferences.paniTokyo,
  }),
  PlaceSchema.parse({
    id: 'place-fukuoka-1',
    cityId: 'city-fukuoka',
    countryId: 'country-jp',
    name: 'Ichiran Main Shop',
    category: 'restaurant',
    shortDescription: 'Late-night ramen stop',
    address: '5-3-2 Nakasu, Hakata Ward, Fukuoka',
    location: { lat: 33.5933, lng: 130.4059 },
    thumbnailUrl: 'https://images.example.com/places/ichiran-main.png',
    tags: ['ramen', 'late-night'],
    sourceReferences: sourceReferences.kwakFukuoka,
  }),
  PlaceSchema.parse({
    id: 'place-fukuoka-2',
    cityId: 'city-fukuoka',
    countryId: 'country-jp',
    name: 'Ohori Park',
    category: 'attraction',
    shortDescription: 'Lakeside walking reset',
    address: '1-2 Ohorikoen, Chuo Ward, Fukuoka',
    location: { lat: 33.5863, lng: 130.3763 },
    thumbnailUrl: 'https://images.example.com/places/ohori-park.png',
    tags: ['park', 'stroll'],
    sourceReferences: sourceReferences.kwakFukuoka,
  }),
  PlaceSchema.parse({
    id: 'place-hanoi-1',
    cityId: 'city-hanoi',
    countryId: 'country-vn',
    name: 'Old Quarter Coffee House',
    category: 'restaurant',
    shortDescription: 'Egg coffee break in the old quarter',
    address: '39 Hang Dieu, Hoan Kiem, Hanoi',
    location: { lat: 21.0328, lng: 105.8487 },
    thumbnailUrl: 'https://images.example.com/places/hanoi-coffee-house.png',
    tags: ['coffee', 'old-quarter'],
    sourceReferences: sourceReferences.wonjiHanoi,
  }),
  PlaceSchema.parse({
    id: 'place-hanoi-2',
    cityId: 'city-hanoi',
    countryId: 'country-vn',
    name: 'Hanoi La Siesta',
    category: 'lodging',
    shortDescription: 'Central stay for a slow evening reset',
    address: '94 Ma May, Hoan Kiem, Hanoi',
    location: { lat: 21.0351, lng: 105.8524 },
    thumbnailUrl: 'https://images.example.com/places/hanoi-la-siesta.png',
    tags: ['hotel', 'central'],
    sourceReferences: sourceReferences.wonjiHanoi,
  }),
  PlaceSchema.parse({
    id: 'place-danang-1',
    cityId: 'city-danang',
    countryId: 'country-vn',
    name: 'My Khe Beach',
    category: 'attraction',
    shortDescription: 'Morning beach walk and coffee route',
    address: 'Vo Nguyen Giap, Son Tra, Da Nang',
    location: { lat: 16.0617, lng: 108.2468 },
    thumbnailUrl: 'https://images.example.com/places/my-khe-beach.png',
    tags: ['beach', 'morning'],
    sourceReferences: sourceReferences.sionDaNang,
  }),
  PlaceSchema.parse({
    id: 'place-danang-2',
    cityId: 'city-danang',
    countryId: 'country-vn',
    name: 'Son Tra Cowork Cafe',
    category: 'restaurant',
    shortDescription: 'Work-friendly brunch cafe near the coast',
    address: '15 An Thuong 26, Ngu Hanh Son, Da Nang',
    location: { lat: 16.0481, lng: 108.2472 },
    thumbnailUrl: 'https://images.example.com/places/son-tra-cowork-cafe.png',
    tags: ['brunch', 'work-friendly'],
    sourceReferences: sourceReferences.sionDaNang,
  }),
  PlaceSchema.parse({
    id: 'place-tokyo-3',
    cityId: 'city-tokyo',
    countryId: 'country-jp',
    name: 'Kiyosumi Garden',
    category: 'attraction',
    shortDescription: 'Calm neighborhood garden stop',
    address: '3-3-9 Kiyosumi, Koto City, Tokyo',
    location: { lat: 35.6786, lng: 139.7988 },
    thumbnailUrl: 'https://images.example.com/places/kiyosumi-garden.png',
    tags: ['garden', 'neighborhood'],
    sourceReferences: sourceReferences.czechjTokyo,
  }),
  PlaceSchema.parse({
    id: 'place-tokyo-4',
    cityId: 'city-tokyo',
    countryId: 'country-jp',
    name: 'Kanda Hostel',
    category: 'lodging',
    shortDescription: 'Compact stay on a city-walk route',
    address: '2-10-2 Kajicho, Chiyoda City, Tokyo',
    location: { lat: 35.6915, lng: 139.7714 },
    thumbnailUrl: 'https://images.example.com/places/kanda-hostel.png',
    tags: ['hostel', 'budget'],
    sourceReferences: sourceReferences.czechjTokyo,
  }),
  PlaceSchema.parse({
    id: 'place-hanoi-3',
    cityId: 'city-hanoi',
    countryId: 'country-vn',
    name: 'Bun Cha Ta',
    category: 'restaurant',
    shortDescription: 'Quick lunch stop before check-in',
    address: '21 Nguyen Huu Huan, Hoan Kiem, Hanoi',
    location: { lat: 21.0342, lng: 105.8536 },
    thumbnailUrl: 'https://images.example.com/places/bun-cha-ta.png',
    tags: ['bun-cha', 'lunch'],
    sourceReferences: sourceReferences.janjanHanoi,
  }),
  PlaceSchema.parse({
    id: 'place-hanoi-4',
    cityId: 'city-hanoi',
    countryId: 'country-vn',
    name: 'Little Charm Hanoi Hostel',
    category: 'lodging',
    shortDescription: 'Budget overnight base near the old quarter',
    address: '44 Hang Bo, Hoan Kiem, Hanoi',
    location: { lat: 21.0348, lng: 105.8477 },
    thumbnailUrl: 'https://images.example.com/places/little-charm-hanoi.png',
    tags: ['hostel', 'budget'],
    sourceReferences: sourceReferences.janjanHanoi,
  }),
];

export const placeSnapshots = [
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-tokyo-1',
    placeId: 'place-tokyo-1',
    capturedAt: '2026-03-18T09:00:00.000Z',
    openingHours: '08:00-14:00',
    menuItems: ['Seafood rice bowl', 'Tamagoyaki skewer'],
    averagePrice: 2200,
    currencyCode: 'JPY',
    isStale: false,
    sourceReferences: sourceReferences.paniTokyo,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-tokyo-2',
    placeId: 'place-tokyo-2',
    capturedAt: '2026-03-18T09:00:00.000Z',
    openingHours: '06:00-17:00',
    cautionNote: 'Temple event hours may vary.',
    isStale: false,
    sourceReferences: sourceReferences.paniTokyo,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-fukuoka-1',
    placeId: 'place-fukuoka-1',
    capturedAt: '2026-03-18T09:15:00.000Z',
    openingHours: '10:00-23:00',
    averagePrice: 1400,
    currencyCode: 'JPY',
    isStale: false,
    sourceReferences: sourceReferences.kwakFukuoka,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-fukuoka-2',
    placeId: 'place-fukuoka-2',
    capturedAt: '2026-03-18T09:15:00.000Z',
    openingHours: 'Always open',
    isStale: false,
    sourceReferences: sourceReferences.kwakFukuoka,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-hanoi-1',
    placeId: 'place-hanoi-1',
    capturedAt: '2026-03-18T09:30:00.000Z',
    openingHours: '07:00-22:00',
    menuItems: ['Egg coffee', 'Yogurt coffee'],
    averagePrice: 90000,
    currencyCode: 'VND',
    isStale: false,
    sourceReferences: sourceReferences.wonjiHanoi,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-hanoi-2',
    placeId: 'place-hanoi-2',
    capturedAt: '2026-03-18T09:30:00.000Z',
    averagePrice: 2400000,
    currencyCode: 'VND',
    lodgingType: 'hotel',
    lodgingRating: 4,
    isStale: false,
    sourceReferences: sourceReferences.wonjiHanoi,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-danang-1',
    placeId: 'place-danang-1',
    capturedAt: '2026-03-18T09:45:00.000Z',
    openingHours: 'Always open',
    cautionNote: 'Weather conditions affect beach access experience.',
    isStale: false,
    sourceReferences: sourceReferences.sionDaNang,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-danang-2',
    placeId: 'place-danang-2',
    capturedAt: '2026-03-18T09:45:00.000Z',
    openingHours: '08:30-20:00',
    menuItems: ['Vietnamese drip coffee', 'Avocado toast'],
    averagePrice: 160000,
    currencyCode: 'VND',
    isStale: false,
    sourceReferences: sourceReferences.sionDaNang,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-tokyo-3',
    placeId: 'place-tokyo-3',
    capturedAt: '2026-03-18T10:00:00.000Z',
    openingHours: '09:00-17:00',
    isStale: false,
    sourceReferences: sourceReferences.czechjTokyo,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-tokyo-4',
    placeId: 'place-tokyo-4',
    capturedAt: '2026-03-18T10:00:00.000Z',
    averagePrice: 12000,
    currencyCode: 'JPY',
    lodgingType: 'hostel',
    lodgingRating: 3,
    isStale: false,
    sourceReferences: sourceReferences.czechjTokyo,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-hanoi-3',
    placeId: 'place-hanoi-3',
    capturedAt: '2026-03-18T10:15:00.000Z',
    openingHours: '11:00-21:00',
    menuItems: ['Bun cha set'],
    averagePrice: 120000,
    currencyCode: 'VND',
    isStale: false,
    sourceReferences: sourceReferences.janjanHanoi,
  }),
  PlaceSnapshotSchema.parse({
    id: 'snapshot-place-hanoi-4',
    placeId: 'place-hanoi-4',
    capturedAt: '2026-03-18T10:15:00.000Z',
    averagePrice: 550000,
    currencyCode: 'VND',
    lodgingType: 'hostel',
    lodgingRating: 2.5,
    isStale: false,
    sourceReferences: sourceReferences.janjanHanoi,
  }),
];

export const courses = [
  CourseSchema.parse({
    id: 'course-pani-tokyo-1',
    youtuberId: 'youtuber-pani-bottle',
    countryId: 'country-jp',
    cityId: 'city-tokyo',
    title: '빠니보틀 도쿄 하루 압축 코스',
    shortDescription: '시장 아침 식사와 아사쿠사 도보 동선을 담은 하루 코스',
    thumbnailUrl: 'https://images.example.com/courses/pani-tokyo-day.png',
    placeItems: [
      { placeId: 'place-tokyo-1', order: 1, stayMinutes: 70 },
      { placeId: 'place-tokyo-2', order: 2, stayMinutes: 90 },
    ],
    tags: ['day-trip', 'market'],
    sourceReferences: sourceReferences.paniTokyo,
    publishedAt: '2026-03-10T00:00:00.000Z',
    isFeatured: true,
  }),
  CourseSchema.parse({
    id: 'course-kwak-fukuoka-1',
    youtuberId: 'youtuber-kwaktube',
    countryId: 'country-jp',
    cityId: 'city-fukuoka',
    title: '곽튜브 후쿠오카 야식 코스',
    shortDescription: '라멘과 공원 산책으로 마무리하는 도심 먹방 루트',
    thumbnailUrl: 'https://images.example.com/courses/kwak-fukuoka-night.png',
    placeItems: [
      { placeId: 'place-fukuoka-1', order: 1, stayMinutes: 60 },
      { placeId: 'place-fukuoka-2', order: 2, stayMinutes: 45 },
    ],
    tags: ['food', 'night'],
    sourceReferences: sourceReferences.kwakFukuoka,
    publishedAt: '2026-03-11T00:00:00.000Z',
  }),
  CourseSchema.parse({
    id: 'course-wonji-hanoi-1',
    youtuberId: 'youtuber-wonji',
    countryId: 'country-vn',
    cityId: 'city-hanoi',
    title: '원지의 하노이 느린 여행 코스',
    shortDescription: '커피 한 잔과 중심가 숙소 체크인으로 이어지는 여유 루트',
    thumbnailUrl: 'https://images.example.com/courses/wonji-hanoi-slow.png',
    placeItems: [
      { placeId: 'place-hanoi-1', order: 1, stayMinutes: 50 },
      { placeId: 'place-hanoi-2', order: 2, stayMinutes: 30 },
    ],
    tags: ['slow-travel', 'lodging'],
    sourceReferences: sourceReferences.wonjiHanoi,
    publishedAt: '2026-03-12T00:00:00.000Z',
  }),
  CourseSchema.parse({
    id: 'course-sion-danang-1',
    youtuberId: 'youtuber-sion',
    countryId: 'country-vn',
    cityId: 'city-danang',
    title: '노마드션 다낭 오전 루트',
    shortDescription: '해변 산책 후 일하기 좋은 브런치 카페로 이어지는 코스',
    thumbnailUrl: 'https://images.example.com/courses/sion-danang-morning.png',
    placeItems: [
      { placeId: 'place-danang-1', order: 1, stayMinutes: 60 },
      { placeId: 'place-danang-2', order: 2, stayMinutes: 120 },
    ],
    tags: ['beach', 'remote-work'],
    sourceReferences: sourceReferences.sionDaNang,
    publishedAt: '2026-03-13T00:00:00.000Z',
  }),
  CourseSchema.parse({
    id: 'course-czechj-tokyo-1',
    youtuberId: 'youtuber-czechj',
    countryId: 'country-jp',
    cityId: 'city-tokyo',
    title: '체코제이 도쿄 동네 산책 코스',
    shortDescription: '정원 산책과 도심 숙소까지 이어지는 가벼운 하루 루트',
    thumbnailUrl: 'https://images.example.com/courses/czechj-tokyo-walk.png',
    placeItems: [
      { placeId: 'place-tokyo-3', order: 1, stayMinutes: 75 },
      { placeId: 'place-tokyo-4', order: 2, stayMinutes: 20 },
    ],
    tags: ['walking', 'neighborhood'],
    sourceReferences: sourceReferences.czechjTokyo,
    publishedAt: '2026-03-14T00:00:00.000Z',
  }),
  CourseSchema.parse({
    id: 'course-janjan-hanoi-1',
    youtuberId: 'youtuber-janjanbari',
    countryId: 'country-vn',
    cityId: 'city-hanoi',
    title: '잔잔바리 하노이 1박 코스',
    shortDescription: '점심과 체크인을 중심으로 압축한 예산형 1박 루트',
    thumbnailUrl: 'https://images.example.com/courses/janjan-hanoi-overnight.png',
    placeItems: [
      { placeId: 'place-hanoi-3', order: 1, stayMinutes: 45 },
      { placeId: 'place-hanoi-4', order: 2, stayMinutes: 20 },
    ],
    tags: ['budget', 'overnight'],
    sourceReferences: sourceReferences.janjanHanoi,
    publishedAt: '2026-03-15T00:00:00.000Z',
  }),
];

export const seedCatalog = {
  curatedYouTubers,
  countries,
  cities,
  places,
  placeSnapshots,
  courses,
};
